# NumPy Deep Dive


In [1]:
import numpy as np

## Array Creation

In [2]:
a = np.array([1, 2, 3])
b = np.zeros((2, 3))
c = np.ones((2, 2))
d = np.eye(3)  # Identity matrix
e = np.random.rand(4, 5)

print("Array a:", a)
print("Zeros b:\n", b)
print("Ones c:\n", c)
print("Identity d:\n", d)
print("Random e:\n", e)

Array a: [1 2 3]
Zeros b:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones c:
 [[1. 1.]
 [1. 1.]]
Identity d:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random e:
 [[0.24161552 0.3444645  0.05884141 0.07261386 0.90077786]
 [0.63557675 0.94311205 0.75751662 0.12640012 0.70957646]
 [0.64789583 0.36186351 0.32175662 0.52327268 0.07186072]
 [0.07886041 0.71962613 0.2036793  0.05096059 0.52642922]]


## Slicing and Indexing

In [3]:
x = np.arange(10)
print("x[2:5]:", x[2:5])
print("x[:3]:", x[:3])
print("x[-3:]:", x[-3:])

x[2:5]: [2 3 4]
x[:3]: [0 1 2]
x[-3:]: [7 8 9]


## Broadcasting Example

In [4]:
A = np.ones((3, 1))
B = np.arange(3)
print("Broadcasted sum:\n", A + B)

Broadcasted sum:
 [[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


## Vectorized vs Loop Performance

In [5]:
import time

N = 1000000
a = np.random.rand(N)
b = np.random.rand(N)

# Vectorized
start = time.time()
c = a + b
print("Vectorized time:", time.time() - start)

# Loop
start = time.time()
c = [a[i] + b[i] for i in range(N)]
print("Loop time:", time.time() - start)

Vectorized time: 0.0015320777893066406
Loop time: 0.17288494110107422


## Linear Algebra with NumPy

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 2]])

print("Dot Product:\n", A @ B)
print("Inverse of A:\n", np.linalg.inv(A))
print("Determinant of A:", np.linalg.det(A))

Dot Product:
 [[ 4  4]
 [10  8]]
Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Determinant of A: -2.0000000000000004
