In [1]:
import numpy as np

# Example matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix addition
C_add = A + B

# Scalar multiplication
C_scalar = 3 * A

# Matrix multiplication
C_mul = A @ B

# Transpose
A_T = A.T

# Identity and zero matrices
I = np.eye(2)
Z = np.zeros((2, 2))

print("A + B =\n", C_add)
print("3 * A =\n", C_scalar)
print("A @ B =\n", C_mul)
print("A^T =\n", A_T)
print("Identity I =\n", I)
print("Zero Z =\n", Z)

A + B =
 [[ 6  8]
 [10 12]]
3 * A =
 [[ 3  6]
 [ 9 12]]
A @ B =
 [[19 22]
 [43 50]]
A^T =
 [[1 3]
 [2 4]]
Identity I =
 [[1. 0.]
 [0. 1.]]
Zero Z =
 [[0. 0.]
 [0. 0.]]
